name: "xf build kite test"

on:
  push:
    branches: [ 'develop', 'main', 'release_**' ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ 'develop', 'main', 'release_**' ]

jobs:
  xf:
    name: xffff
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Trigger a Buildkite Build
        uses: "buildkite/trigger-pipeline-action@v2.0.0"
        env:
          BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.TRIGGER_BK_BUILD_TOKEN_ENV_1 }}
          pipeline: "nnnnnnnnnnnn/notwell"
          branch: "develop"
          commit: "HEAD"
          message: ":github: Triggered from a GitHub Action"
          build_env_vars: '{"TRIGGERED_FROM_GHA": "true"}'
          build_meta_data: '{"FOO": "bar"}'
          ignore_pipeline_branch_filter: true